*** Variables ***
#Registration
${RegForm_firstName}                            xpath=//input[@name='first_name']
${RegForm_lastName}                             xpath=//input[@name='last_name']
${RegForm_businessName}                         xpath=//input[@name='business_name']
${RegForm_email}                                xpath=//input[@name='email']
${RegForm_ThankYou}                             xpath=//h2/strong[normalize-space(text())='Thank you!']


